version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "15:00"
    timezone: Europe/Stockholm
  open-pull-requests-limit: 10
  target-branch: develop
